"""Retrieval comparison harness: dense vs hybrid search, scored against a
human-labeled query set.

DESIGN RATIONALE (read before modifying):

1. Two full RagServiceFactory instances are built -- one per retrieval_mode --
   rather than constructing SemanticSearchService/HybridSearchService by hand.
   factory.py is the single source of truth for HOW those services get wired
   (including the mandatory HybridSearchService.refresh_index() call before
   first use). Bypassing it would risk testing wiring that doesn't match
   production. Both factories point at the SAME database file, so any score
   difference is attributable to retrieval method, not corpus drift.

2. Labeled queries are loaded from an external JSON file, never generated by
   this script. Ground truth must stay independent of the system under test;
   generating labels here would let bugs in generation logic favor whichever
   retriever happens to match that bug.

3. Scoring functions type only against SemanticSearchResult (the shared,
   Pydantic-validated contract both services return) -- never against
   SemanticSearchService or HybridSearchService directly. This is required
   for the module to keep working unmodified if a third retrieval mode
   (e.g. cross-encoder reranking) is added later in config.py/factory.py.

4. Three metrics are computed per query: precision@k (how much of the top-k
   is relevant), recall@k (how much of all relevant chunks were found),
   and NDCG@k (rewards relevant chunks appearing EARLIER in the ranking,
   not just anywhere in the top-k). Precision/recall alone can't distinguish
   a retriever that ranks the right chunk 1st from one that ranks it 5th.

5. Each RagServiceFactory is closed in a `finally` block immediately after
   its queries finish, so a mid-loop exception on the hybrid-mode factory
   can never leak the dense-mode factory's SQLAlchemy engine/connections.
"""

from __future__ import annotations

import csv
import json
import math
import os
from dataclasses import dataclass, field
from pathlib import Path

from academic_literature_rag.app.factory import RagServiceFactory
from academic_literature_rag.config import AppConfig
from academic_literature_rag.models.semantic_search_result import SemanticSearchResult


# --------------------------------------------------------------------------
# Data model: what one labeled example looks like, and what one query's
# score looks like. Kept as frozen dataclasses so results can't be mutated
# accidentally once computed -- an eval report should be an immutable record.
# --------------------------------------------------------------------------

@dataclass(frozen=True)
class LabeledQuery:
    """One human-labeled evaluation example.

    relevant_chunk_ids is the ground-truth set: every text_chunk_id a human
    reviewer confirmed actually answers `query`. This class makes no claim
    about HOW that set was produced -- see module docstring, point 2.
    """

    query: str
    relevant_chunk_ids: frozenset[str]


@dataclass(frozen=True)
class QueryScore:
    """Retrieval metrics for one query, under one retrieval mode."""

    retrieval_mode: str
    query: str
    precision_at_k: float
    recall_at_k: float
    ndcg_at_k: float
    retrieved_chunk_ids: tuple[str, ...]


@dataclass(frozen=True)
class EvalReport:
    """Full comparison report across all queries and both retrieval modes."""

    scores: list[QueryScore] = field(default_factory=list)

    def mean_by_mode(self) -> dict[str, dict[str, float]]:
        """Average each metric per retrieval_mode, for a top-line summary."""

        modes: dict[str, list[QueryScore]] = {}
        for score in self.scores:
            modes.setdefault(score.retrieval_mode, []).append(score)

        return {
            mode: {
                "precision_at_k": sum(s.precision_at_k for s in items) / len(items),
                "recall_at_k": sum(s.recall_at_k for s in items) / len(items),
                "ndcg_at_k": sum(s.ndcg_at_k for s in items) / len(items),
            }
            for mode, items in modes.items()
        }

    def to_csv(self, path: Path) -> None:
        """Write one row per (query, mode) so results can be diffed/audited."""

        with path.open("w", newline="", encoding="utf-8") as handle:
            writer = csv.writer(handle)
            writer.writerow(
                ["retrieval_mode", "query", "precision_at_k", "recall_at_k", "ndcg_at_k"]
            )
            for score in self.scores:
                writer.writerow(
                    [
                        score.retrieval_mode,
                        score.query,
                        f"{score.precision_at_k:.4f}",
                        f"{score.recall_at_k:.4f}",
                        f"{score.ndcg_at_k:.4f}",
                    ]
                )


# --------------------------------------------------------------------------
# Loading ground truth. This function is intentionally "dumb": it trusts
# the JSON file completely and does zero relevance judgment itself.
# --------------------------------------------------------------------------

def load_labeled_queries(path: Path) -> list[LabeledQuery]:
    """Load labeled queries from a JSON file the caller supplies.

    Expected file shape:
    [
      {"query": "What is AST-GRU?", "relevant_chunk_ids": ["<uuid>", "<uuid>"]},
      ...
    ]
    """

    raw = json.loads(path.read_text(encoding="utf-8"))
    return [
        LabeledQuery(
            query=item["query"],
            relevant_chunk_ids=frozenset(str(cid) for cid in item["relevant_chunk_ids"]),
        )
        for item in raw
    ]


# --------------------------------------------------------------------------
# Metrics. Each function does exactly one calculation and is unit-testable
# in isolation without touching the database or either retrieval service.
# --------------------------------------------------------------------------

def _dcg_at_k(relevant_ids: frozenset[str], ranked_ids: list[str], k: int) -> float:
    """Discounted Cumulative Gain: relevant chunks ranked earlier score higher."""

    return sum(
        1.0 / math.log2(rank + 1)
        for rank, chunk_id in enumerate(ranked_ids[:k], start=1)
        if chunk_id in relevant_ids
    )


def _ideal_dcg_at_k(relevant_count: int, k: int) -> float:
    """Best-possible DCG@k if every relevant chunk were ranked first. Used to
    normalize DCG into NDCG so scores are comparable across queries with
    different numbers of relevant chunks."""

    return sum(1.0 / math.log2(rank + 1) for rank in range(1, min(relevant_count, k) + 1))


def score_query(
    *,
    retrieval_mode: str,
    labeled_query: LabeledQuery,
    results: list[SemanticSearchResult],
    top_k: int,
) -> QueryScore:
    """Compute precision@k, recall@k, and NDCG@k for one retrieval run."""

    ranked_ids = [str(result.text_chunk_id) for result in results[:top_k]]
    relevant = labeled_query.relevant_chunk_ids

    hits = sum(1 for chunk_id in ranked_ids if chunk_id in relevant)
    precision = hits / top_k if top_k else 0.0
    recall = hits / len(relevant) if relevant else 0.0

    dcg = _dcg_at_k(relevant, ranked_ids, top_k)
    ideal_dcg = _ideal_dcg_at_k(len(relevant), top_k)
    ndcg = dcg / ideal_dcg if ideal_dcg > 0 else 0.0

    return QueryScore(
        retrieval_mode=retrieval_mode,
        query=labeled_query.query,
        precision_at_k=precision,
        recall_at_k=recall,
        ndcg_at_k=ndcg,
        retrieved_chunk_ids=tuple(ranked_ids),
    )


# --------------------------------------------------------------------------
# Orchestration: build one factory per mode, run every labeled query
# through it, score each, always close the factory afterward.
# --------------------------------------------------------------------------

def run_eval(
    *,
    retrieval_mode: str,
    labeled_queries: list[LabeledQuery],
    top_k: int = 5,
    env_overrides: dict[str, str] | None = None,
) -> list[QueryScore]:
    """Build a RagServiceFactory for one retrieval_mode and score it against
    every labeled query. See module docstring point 1 and 5 for why the
    factory is built fresh here and always closed in `finally`.
    """

    env = dict(os.environ)
    env["RAG_RETRIEVAL_MODE"] = retrieval_mode
    if env_overrides:
        env.update(env_overrides)

    config = AppConfig.from_env(env)
    factory = RagServiceFactory.from_config(config)

    try:
        search_service = factory.create_core_services().semantic_search_service

        scores: list[QueryScore] = []
        for labeled_query in labeled_queries:
            results = search_service.search(labeled_query.query, top_k=top_k)
            scores.append(
                score_query(
                    retrieval_mode=retrieval_mode,
                    labeled_query=labeled_query,
                    results=results,
                    top_k=top_k,
                )
            )
        return scores
    finally:
        factory.close()


def compare_retrieval_modes(
    *,
    labeled_queries_path: Path,
    top_k: int = 5,
    modes: tuple[str, ...] = ("dense", "hybrid"),
) -> EvalReport:
    """Run the full dense-vs-hybrid comparison and return a combined report.

    Adding a third mode later means adding its string to `modes` -- nothing
    else in this file needs to change, as long as config.py/factory.py
    already know how to build a service for that mode string.
    """

    labeled_queries = load_labeled_queries(labeled_queries_path)

    report = EvalReport()
    for mode in modes:
        report.scores.extend(
            run_eval(retrieval_mode=mode, labeled_queries=labeled_queries, top_k=top_k)
        )

    return report


if __name__ == "__main__":
    report = compare_retrieval_modes(
        labeled_queries_path=Path("tests/fixtures/labeled_queries.json"),
        top_k=5,
    )

    for mode, means in report.mean_by_mode().items():
        print(mode, means)

    report.to_csv(Path("retrieval_comparison.csv"))
